version: '3.8'

services:

  ### collection, storage and visualization of various information

  # Grafana Tempo (tracing)
  tempo:
    image: grafana/tempo:2.2.2
    command:
      - --config.file=/etc/tempo-config.yaml
      - --log.level=debug
    volumes:
      - D:/Programing/GithubRepos/shoppingManager/docker/tempo/tempo.yaml:/etc/tempo-config.yaml:ro
      - D:/Programing/GithubRepos/shoppingManager/docker/tempo/tempo-data:/tmp/tempo
    ports:
      - "3110:3100"
      - "9411:9411"

  # Grafana Loki (logging)
  loki:
    image: grafana/loki:main
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"

  # Metrics(JVM statistic , Thread Count , Heap memory , Statistics …)
  prometheus:
    image: prom/prometheus:v2.46.0
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  # Collect and display all information
  grafana:
    image: grafana/grafana:10.1.0
    volumes:
      - ./docker/grafana:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"

  # Zookeeper configuration (needed for managing Kafka clusters)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181  # Port on which Zookeeper listens for client connections (default 2181)
      ZOOKEEPER_TICK_TIME: 2000    # Interval in milliseconds used by Zookeeper for internal timers (2000 ms)
      # tickTime is the basic unit of time in milliseconds used by Zookeeper for various internal operations
      # like sending heartbeat messages between Zookeeper servers and clients, session management, and leader election.
      # Session Timeout (maxClientCnxns) - Time after which a client session is considered invalid if the client does not send heartbeat messages.
      # For example, with tickTime set to 2000 ms and sessionTimeout set to 10 tickTime, the client session will expire after 20 seconds without heartbeat messages.

  # Kafka broker configuration
  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper  # Indicates that the Kafka broker should start after Zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'  # Address of the Zookeeper to which Kafka connects
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT  # Defines security protocols for Kafka listeners; in this case, PLAINTEXT and PLAINTEXT_INTERNAL.
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092  # Configuration parameter defining how Kafka broker advertises its listeners to other systems.
      # This setting helps clients and other brokers to connect to the Kafka broker.
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  # Sets the replication factor for the offsets topic. Value 1 means no replication, acceptable for testing only.
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1  # Sets the minimum number of in-sync replicas required for transaction logs.
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1  # Sets the replication factor for transaction state logs. Value 1 means no replication.
